# Cloudflare Pages configuration for Remix
name = "personal-portfolio"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# For Pages deployment
pages_build_output_dir = "build/client"

# Optional: KV namespace for theme persistence
[[kv_namespaces]]
binding = "MY_KV"
id = "MY_KV"
preview_id = "MY_KV"
