# Cloudflare Pages configuration for Remix
# This file is used for Cloudflare Pages deployment
# For direct wrangler deployment, you'll need to create a Worker first

# Remove the name field for Pages deployment
# name = "personal-portfolio"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# For Pages, the main entry point is handled automatically
# main = "./build/server/index.js"

# Optional: KV namespace for theme persistence
[[kv_namespaces]]
binding = "MY_KV"
id = "MY_KV"
preview_id = "MY_KV"
