name = "personal-portfolio"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
main = "./build/server/index.js"

[env.production]
name = "personal-portfolio"

[[kv_namespaces]]
binding = "MY_KV"
id = "MY_KV"
preview_id = "MY_KV"
